Document: purple-carbons
Title: Debian purple-carbons Manual
Author: <insert document author here>
Abstract: This manual describes what purple-carbons is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/purple-carbons/purple-carbons.sgml.gz

Format: postscript
Files: /usr/share/doc/purple-carbons/purple-carbons.ps.gz

Format: text
Files: /usr/share/doc/purple-carbons/purple-carbons.text.gz

Format: HTML
Index: /usr/share/doc/purple-carbons/html/index.html
Files: /usr/share/doc/purple-carbons/html/*.html
